AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS API Gateway with a Lambda Integration
Parameters:
  LambdaFuncName:
    Type: String
    Default: "pythonTest"
Resources:
  FunctionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Path: /
    Type: AWS::IAM::Role
  LambdaFunc:
    Properties:
      CodeUri: ./lambda-deploy.zip
      Description: AWS Lambda function
      FunctionName:
        Ref: "LambdaFuncName"
      Events:
        ExecuteFunc:
          Properties:
            Method: any
            Path: /
          Type: Api
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - FunctionRole
          - Arn
      Runtime: python3.7
      Timeout: 40
    Type: AWS::Serverless::Function
